### ISSUE TITLE
Error creatng new branch: HttpError: refs/heads/ is not a valid ref name

### ISSUE THREAD

**Issue by yougikou** [LasyIsLazy/github-upload-action#13]
Hi,

I got below error. It seems maybe not support master branch. Does this action only support main branch?

Error: Error creatng new branch: HttpError: refs/heads/ is not a valid ref name.
Error: checkBranch failed: HttpError: refs/heads/ is not a valid ref name.

**Comment by LasyIsLazy** [comment]
> Hi,
> 
> I got below error. It seems maybe not support master branch. Does this action only support main branch?
> 
> Error: Error creatng new branch: HttpError: refs/heads/ is not a valid ref name. Error: checkBranch failed: HttpError: refs/heads/ is not a valid ref name.

Hi,
maybe you can check your options. There is an option named `branch-name` which should be `master` and I didn't see that in your log.
Or you can create the branch manully.

**Comment by yougikou** [comment]
Thank you. Yes. You are right. I set up the branch name, then everything goes fine. Thanks.
