### ISSUE TITLE
Support uploading to a specific branch

### ISSUE THREAD

**Issue by rajbos** [LasyIsLazy/github-upload-action#2]
Currently all files are uploaded to the default branch, as that is what the GitHub API uses by default. I want to pass in a parameter indicating the branch name to use for uploading the file. 

As a requirement I'd say that the branch already has to exist. Creating it is not necessary for me.

# Changes needed
- [ ] Add an optional parameter to the action to specify the branch name
- [ ] Add the extra parameter to the PUT call in upload.js, see [documentation](https://docs.github.com/en/rest/reference/repos#create-or-update-file-contents)

https://github.com/LasyIsLazy/github-upload-action/blob/20142a091175a549a644954ee979f16f9e65a33d/upload.js#L49-L54

I'd be happy to help working on this :-)

**Comment by LasyIsLazy** [comment]
I'd be thankful if you can make a PR for this.
Additional, There may be several points to note:
- What will the GitHub API do if the branch is not existed?
- Which structure should we use for the extra parameter to the PUT call?

**Comment by rajbos** [comment]
I'd say create the branch if it doesn't exist yet. Currently the upload just fails with a non-descriptive error. Will see if I can add that as well, maybe tomorrow.

See the progress here #5
